apiVersion: v1 #Service lives in the core API group (stable).
kind: Service #Declares a Service object — a stable network endpoint that routes traffic to one or more Pods.
metadata:
  name: llmops-service #The Service name. Inside the cluster you can reach it by this DNS name
spec:
  selector:
    app: llmops-app #The Service routes traffic to Pods that have the label app=llmops-app. This must match the labels on your Deployment's Pod template (labels: app: llmops-app)
  ports:
    - port: 80 #the Service port (the port other Pods in the cluster use to contact the service).
      targetPort: 8501  # default port for Streamlit,the port on the container (the Pod) receiving traffic. This should match what your app listens on (Streamlit defaults to 8501).
  type: NodePort #Exposes the Service on a port on each Node. Kubernetes will allocate a port from the NodePort range (by default 30000–32767) unless you set one explicitly.